version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: commercehub-mongo
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: ./CommerceHub.API
    container_name: commercehub-api
    ports:
      - "5001:8080"
    depends_on:
      - mongodb
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=CommerceHubDb

volumes:
  mongo-data: